### ISSUE TITLE
test.py failure

### ISSUE THREAD

**Issue by pgajdos** [jsommers/pytricia#26]
test.py fails for me with:
```
[    4s] ======================================================================
[    4s] ERROR: testRaw (test.PyTriciaTests)
[    4s] ----------------------------------------------------------------------
[    4s] Traceback (most recent call last):
[    4s]   File "/home/abuild/rpmbuild/BUILD/pytricia-1.0.0/test.py", line 415, in testRaw
[    4s]     pyt = pytricia.PyTricia(32, socket.AF_INET, True)
[    4s] ValueError: Error parsing prefix length or address family
[    4s] 
[    4s] ======================================================================
[    4s] ERROR: testRawIP6 (test.PyTriciaTests)
[    4s] ----------------------------------------------------------------------
[    4s] Traceback (most recent call last):
[    4s]   File "/home/abuild/rpmbuild/BUILD/pytricia-1.0.0/test.py", line 435, in testRawIP6
[    4s]     pyt = pytricia.PyTricia(128, socket.AF_INET6, True)
[    4s] ValueError: Error parsing prefix length or address family
[    4s] 
[    4s] ----------------------------------------------------------------------
```
This is with both python 2.7 and python 3.7.

**Comment by pgajdos** [comment]
I do not experience it with 1.0.1.
