### ISSUE TITLE
Error when accessing very similar CIDR blocks depnding on order of insertion

### ISSUE THREAD

**Issue by GabrielZigelboim** [jsommers/pytricia#38]
pyt =	pytricia.PyTricia()
pyt['2400:0:860::/44']='k'
pyt['2400:0:840::/43']='l'
pyt['2400:0:840::/43']
Out[85]: 'l'
pyt['2400:0:860::/44']
Out[86]: 'k'
pyt =	pytricia.PyTricia()
pyt['2400:0:840::/43']='l'
pyt['2400:0:860::/44']='k'
pyt['2400:0:840::/43']
Traceback (most recent call last):
  File ".env\lib\site-packages\IPython\core\interactiveshell.py", line 3526, in run_code
    exec(code_obj, self.user_global_ns, self.user_ns)
  File "<ipython-input-87-5805227ad9df>", line 4, in <module>
    pyt['2400:0:840::/43']
KeyError: 'Prefix not found.'
pyt['2400:0:860::/44']
Traceback (most recent call last):
  File ".env\lib\site-packages\IPython\core\interactiveshell.py", line 3526, in run_code
    exec(code_obj, self.user_global_ns, self.user_ns)
  File "<ipython-input-90-c22e811ed9e0>", line 1, in <module>
    pyt['2400:0:860::/44']
KeyError: 'Prefix not found.

**Comment by GabrielZigelboim** [comment]
invalid_keys = [cidr for cidr in pyt if cidr not in pyt]
returns in that case not empty 
😲

**Comment by jsommers** [comment]
Creation needs to be pyt = pytricia.PyTricia(128)
